package com.limei.movieapp.huiying.unit;

/**
 * Created by Administrator on 2018/8/27.
 */

public class WebAdds {
    public static String HTTPALLMOVES;
    public static String HTTPBOFANGQIAN;
    public static String HTTPBOFANGWAN;
    public static String HTTPCHONGZHI;
    public static String HTTPDELEHUANCUN;
    public static String HTTPDENGLU;
    public static String HTTPDIANYINGXIANG;
    public static String HTTPDIANZAN;
    public static String HTTPDINGDANJILU;
    public static String HTTPDUANXIN;
    public static String HTTPFENLEI;
    public static String HTTPFENXIANG;
    public static String HTTPGOUMAI;
    public static String HTTPGOUPIAO;
    public static String HTTPGUANYUWE;
    public static String HTTPHUANCUNWAN;
    public static String HTTPISQQ;
    public static String HTTPISWX;
    public static String HTTPLIJIGOUMAI;
    public static String HTTPMXIUGAINICHENG;
    public static String HTTPMYINFO;
    public static String HTTPNEWSS;
    public static String HTTPNEWSSCONTENT;
    public static String HTTPQIANBAOMINGXI;
    public static String HTTPQUXIAO;
    public static String HTTPREMENSOU;
    public static String HTTPSHYANGCHUANJINDU;
    public static String HTTPSOUSUO;
    public static String HTTPWANCHENGFANGYING;
    public static String HTTPWODEZHANGHU;
    public static String HTTPXIAOXI;
    public static String HTTPXIAOXIXIANGQING;
    public static String HTTPXIUGAITOUXIANG;
    public static String HTTPZENGPIAOJILU;
    public static String HTTPZHENGZAIFANGYING;
    public static String HTTPZHENGZAIXIANGQING;
    public static String YUMING = "http://hy.shiduweb.com/";

    static {
        StringBuilder localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("adysms_php/api_demo/tel_dx.php");
        HTTPDUANXIN = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("signs.html");
        HTTPDENGLU = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Films.html");
        HTTPGOUPIAO = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Film_detailss.html");
        HTTPDIANYINGXIANG = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("purchases.html");
        HTTPGOUMAI = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("classifys.html");
        HTTPFENLEI = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("AllFilms.html");
        HTTPALLMOVES = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Hots.html");
        HTTPREMENSOU = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("searchs.html");
        HTTPSOUSUO = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("FilmPayments.html");
        HTTPLIJIGOUMAI = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("newss.html");
        HTTPNEWSS = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("news_detailss.html");
        HTTPNEWSSCONTENT = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("fabulouss.html");
        HTTPDIANZAN = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("informations.html");
        HTTPXIAOXI = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("information_detailss.html");
        HTTPXIAOXIXIANGQING = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("MyInformations.html");
        HTTPMYINFO = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("nicknames.html");
        HTTPMXIUGAINICHENG = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("AboutUss.html");
        HTTPGUANYUWE = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("MyAccounts.html");
        HTTPWODEZHANGHU = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Recharges.html");
        HTTPCHONGZHI = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Recharge_detailss.html");
        HTTPQIANBAOMINGXI = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("showings.html");
        HTTPZHENGZAIFANGYING = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("CompleteShowings.html");
        HTTPWANCHENGFANGYING = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("showing_detailss.html");
        HTTPZHENGZAIXIANGQING = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("isQQappids.html");
        HTTPISQQ = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("isWxappids.html");
        HTTPISWX = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("GiveRecords.html");
        HTTPZENGPIAOJILU = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("FilmPaymentRecords.html");
        HTTPDINGDANJILU = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("HeadPortraits.html");
        HTTPXIUGAITOUXIANG = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("BeforePlayings.html");
        HTTPBOFANGQIAN = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("PlayCompletions.html");
        HTTPBOFANGWAN = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Gives.html");
        HTTPFENXIANG = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("Exitsaves.html");
        HTTPSHYANGCHUANJINDU = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("cancelGives.html");
        HTTPQUXIAO = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("caches.html");
        HTTPHUANCUNWAN = localStringBuilder.toString();
        localStringBuilder = new StringBuilder();
        localStringBuilder.append(YUMING);
        localStringBuilder.append("DeleteCaches.html");
        HTTPDELEHUANCUN = localStringBuilder.toString();
    }
}


